package:
  name: yarcc_easy
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/wolfiex/YARCC_easy_submit.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - argparse

test:
  imports:

about:
  home: https://github.com/wolfiex/YARCC_easy_submit
  license: MIT
  license_file: LICENSE

extra:
  maintainers:
   - Daniel Ellis
